version: 2.1
aliases:
  - &defaults
    working_directory: ~/app
    machine:
      docker_layer_caching: true

  - &authenticate-dockerhub
    name: Authenticate to Docker Hub
    command: echo "$DOCKER_HUB_PWD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin

  - &build-image
    name: Build image
    command: ./config/build-image

workflows:
  version: 2
  ci-pipeline:
    jobs:
      - publish

jobs:

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: *build-image
      - run: *authenticate-dockerhub
      - run:
          name: Push image
          command: ./config/push-image
